version: "3.7"

services:

  minio:
    image: 'bitnami/minio:latest'
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minio-root-user
      - MINIO_ROOT_PASSWORD=minio-root-password

  redis:
    container_name: cache
    image: redis:8.0-M02-alpine
    restart: always
    ports:
      - "6379:6379"
