spring:
  application:
    name: kufar-spy-bot

  flyway:
    enabled: false


server:
  port: 8085

rest-client:
  user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36

telegram:
  token: sdflkhdkjfghkjdfghjkdghjkdfghjkdghd
  name: KufarSpy