spring:

  flyway:
    enabled: false

  config:
    import: "configserver:"
  cloud:
    config:
      import-check:
        enabled: false
      discovery:
        enabled: true
        service-id: configserver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true