spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  flyway:
    enabled: false

  cloud:
    config:
      import-check:
        enabled: false
      discovery:
        enabled: true
        service-id: configserver

server:
  port: 8085

eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: false
