spring:
  application:
    name: kufar-bot

rest-client:
  user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36

server:
  port: 8085

telegram:
  token: sdflkhdkjfghkjdfghjkdghjkdfghjkdghd
  name: KufarSpy